---
apiVersion: {{ .Values.esoversion }}
kind: ExternalSecret
metadata:
  name: config-demo-secret
  namespace: config-demo
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: aws-secretsmanager-accesskey-store
    kind: {{ .Values.secretStore.kind }}
  target:
    name: config-demo-secret
    template:
      type: Opaque
    data:
      secret: "{{ `{{ .configdemo_secret }}` }}"
  data:
    - secretKey: configdemo_secret
      remoteRef:
        key: {{ .Values.configdemosecret.key }}
        propert: secret
