---
global:
  pattern: multicloud-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
main:
  clusterGroupName: hub
  gitops:
    channel: "gitops-1.18"
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: "0.9.*"
