---
global:
  pattern: multicloud-gitops
  secretStore:
    backend: "vault"
    backend: "aws-secrets-manager"
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: "0.9.*"
